# docker-compose.yml
version: '3.8'

services:
  # Base de datos PostgreSQL
  db:
    image: postgres:17.3
    container_name: appsali_db
    environment:
      POSTGRES_DB: alitools
      POSTGRES_USER: ali_user
      POSTGRES_PASSWORD: ali_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Aplicación Django
  web:
    build: .
    container_name: appsali_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - pdf_storage:/app/media/pdfs
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_NAME=alitools
      - DB_USER=ali_user
      - DB_PASSWORD=ali_password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    restart: unless-stopped

  # pgAdmin - Interface web para PostgreSQL
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: appsali_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@appsali.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
  pdf_storage:
  pgadmin_data: