# Generated by Django 5.2.1 on 2025-06-20 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('proveedores', '0002_alter_proveedor_codigo_erp'),
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='provider',
        ),
        migrations.AddField(
            model_name='project',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='project',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo del Proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre del Proyecto'),
        ),
    ]
