# Generated by Django 5.2.1 on 2025-06-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='codigo_erp',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código en ERP'),
        ),
    ]
