# Generated by Django 5.2.1 on 2025-06-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(max_length=255, verbose_name='Nombre Comercial')),
                ('rfc', models.CharField(max_length=20, unique=True, verbose_name='RFC')),
                ('erp_id', models.IntegerField(unique=True, verbose_name='ID en ERP')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razon_social'],
            },
        ),
    ]
